#! /bin/sh
bspc monitor DisplayPort-2 -d I II III IV V VI VII VIII IX X

~/.screenlayout/omni.sh &

sxhkd &
# Get rid of X
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc config active_border_color '#0C1115'
bspc config normal_border_color '#0C1115'
bspc config focused_border_color '#E97451'

bspc config top_padding 55

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config single_monocle true
bspc config gapless_monocle false

bspc config focus_follows_pointer true
bspc config pointer_modifier mod4


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2' bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Conky state=floating manage=off

# ~/scripts/watcher.sh

picom --config ~/.config/picom/picom.conf &

#dunst &
#redshift-gtk -l 59.9139:10.7522 &
#polybar topleft &
#polybar topright &
#volumeicon &
#blueberry-tray &
#nm-applet &
#variety &
~/scripts/autostart.sh &
