#! /bin/sh

killall dunst;notify-send foo
pgrep redshift | xargs -n1 kill -9

sxhkd &
# Get rid of X
xsetroot -cursor_name left_ptr &
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc config active_border_color '#0C1115'
bspc config normal_border_color '#0C1115'
bspc config focused_border_color '#0F9B8E'

bspc config top_padding 28

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config single_monocle true
bspc config gapless_monocle false


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2' bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

picom --config ~/.config/picom/picom.conf
dunst
redshift -l 59.6633:10.6307
