#!/bin/sh
sxhkd &
# Get rid of X
xsetroot -cursor_name left_ptr &
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc config active_border_color '#0C1115'
bspc config normal_border_color '#0C1115'
bspc config focused_border_color '#0F9B8E'

bspc config top_padding 27

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config single_monocle true
bspc config gapless_monocle true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2' 
bspc rule -a mplayer2 state=floating
bspc rule -a discord desktop='^5' state=floating center=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a android-studio state=floating border=off follow=on
bspc rule -a java state=floating border=off follow=on

# ~/scripts/watcher.sh &
~/scripts/autostart.sh &

wmname LG3D
